modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="le_epic_mod"
version="1.0.0"
displayName="Le Epic Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="maxbe"

[[dependencies.le_epic_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




